version: 2

jobs:
  build:
    branches:
      ignore:
        - gh-pages
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run:
          command: |
            sudo -E apt-get -yq update
            sudo -E apt-get -yq --no-install-suggests --no-install-recommends --force-yes install dvipng texlive-latex-base texlive-latex-extra
            wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
            chmod +x miniconda.sh && ./miniconda.sh -b -p ~/miniconda
            export PATH="~/miniconda/bin:$PATH"
            conda update --yes --quiet conda
            conda create -n testenv --yes --quiet python=3
            source activate testenv
            conda install --yes pip numpy scipy scikit-learn matplotlib sphinx sphinx_rtd_theme numpydoc pillow keras pandas tensorflow
            pip install sphinx-gallery imblearn
            pip install .
            cd doc
            make html
      - store_artifacts:
          path: doc/_build/html
          destination: doc
      - store_artifacts:
          path: ~/log.txt
      - persist_to_workspace:
          root: doc/_build/html
          paths: .
      - attach_workspace:
          at: doc/_build/html
      - run: ls -ltrh doc/_build/html
      - deploy:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              git config --global user.email $EMAIL
              git config --global user.name $USERNAME
              git clone $CIRCLE_REPOSITORY_URL out
              cd out
              git checkout gh-pages || git checkout --orphan gh-pages
              git rm -rf .
              cp -R ../doc/_build/html/* ./
              touch .nojekyll
              mkdir .circleci
              cp -a ../.circleci/. .circleci/.
              git add -A
              git commit -m "Automated doc html deployment for branch: $CIRCLE_BRANCH, commit $CIRCLE_SHA1"
              git push origin gh-pages
            fi
